version: "3"
services:
  cache:
    build: .
    image: cache
    environment:
      OPENAI_API_KEY: "[REPLACE]"
      DB_URL: "sqlite:////data/database.db"
      INDEX_PATH: "/data/faiss.index"
      MODEL: "gpt-3.5" #Can be replaced to "gpt-4" or "gpt-

    volumes:
      - ./cache:/data
    ports:
      - 8080:8080
